### ISSUE TITLE
When to set connected peripheral

### ISSUE THREAD

**Issue by superyl** [ironsheep/ISPLowEnergyManager#2]
Hello! 

  I'm trying to study this project and I found that you put  self.cbpConnectedDevice = peripheral; in - (void) connectPeripheral:(CBPeripheral*)peripheral instead of the CoreBluetooth callback. Did you do this on purpose? Just curious:)

**Comment by ironsheep** [comment]
Yes it's really being set in **ISPLowEnergyMananger::connectPeripheral:**  Which is intended to be invoked when the user has selected that peripheral she would like to use.

While you are correct in shortly thereafter the delegate will be called, we stash this selection in the property to remember the peripheral being used.  Is you take a look at the delegate handler **centralManager:didFailToConnectPeripheral:error:** you will see that it will clear this property should the connection to the peripheral actually fail.

This help?

-Stephen
